# Generated by Django 6.0 on 2026-01-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_perfil', models.CharField(blank=True, max_length=50)),
                ('perfil_activo', models.BooleanField(default=True)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugar_nacimiento', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_cedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estado_civil', models.CharField(max_length=50)),
                ('licencia_conducir', models.CharField(blank=True, max_length=6)),
                ('telefono_celular', models.CharField(max_length=15)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=50)),
                ('direccion_domiciliaria', models.CharField(max_length=50)),
                ('sitio_web', models.URLField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_horas', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('entidad_patrocinadora', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=60)),
                ('email_patrocinadora', models.EmailField(blank=True, max_length=60)),
                ('activar_en_front', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='cursos/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_desempenado', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('lugar_empresa', models.CharField(max_length=50)),
                ('email_empresa', models.EmailField(blank=True, max_length=100)),
                ('sitio_web_empresa', models.URLField(blank=True, max_length=100)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=60)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion_funciones', models.TextField(max_length=500)),
                ('activar_en_front', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='certificados_laborales/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('activar_en_front', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('fecha_producto', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activar_en_front', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=50)),
                ('fecha_reconocimiento', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('entidad_patrocinadora', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=60)),
                ('activar_en_front', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='reconocimientos/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('estado_producto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor_bien', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activar_en_front', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales')),
            ],
        ),
    ]
