# Generated by Django 6.0 on 2026-01-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_de_vida', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursorealizado',
            options={'verbose_name': 'Formación realizada', 'verbose_name_plural': 'Formaciones realizadas'},
        ),
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'verbose_name': 'Información personal', 'verbose_name_plural': 'Información personal'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'verbose_name': 'Experiencia profesional', 'verbose_name_plural': 'Experiencia profesional'},
        ),
        migrations.AlterModelOptions(
            name='productoacademico',
            options={'verbose_name': 'Producción académica', 'verbose_name_plural': 'Producción académica'},
        ),
        migrations.AlterModelOptions(
            name='productolaboral',
            options={'verbose_name': 'Producción laboral', 'verbose_name_plural': 'Producción laboral'},
        ),
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'verbose_name': 'Acreditación', 'verbose_name_plural': 'Acreditaciones'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'verbose_name': 'Producto en venta', 'verbose_name_plural': 'Listado de productos en venta'},
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='activar_en_front',
            field=models.BooleanField(default=True, verbose_name='Visible/no visible'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción de la formación'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='email_patrocinadora',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Correo electrónico institucional'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='entidad_patrocinadora',
            field=models.CharField(max_length=100, verbose_name='Institución patrocinadora'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de incorporación'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable de contacto'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='nombre_curso',
            field=models.CharField(max_length=100, verbose_name='Formación realizada'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales', verbose_name='Perfil registrado'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='ruta_certificado',
            field=models.FileField(blank=True, null=True, upload_to='cursos/', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número de contacto institucional'),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='total_horas',
            field=models.IntegerField(verbose_name='Horas de formación'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=60, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion_perfil',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descripción de perfil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direccion_domiciliaria',
            field=models.CharField(max_length=50, verbose_name='Dirección de residencia'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dirección laboral'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(max_length=50, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licencia_conducir',
            field=models.CharField(blank=True, max_length=6, verbose_name='Licencia de conducir vigente'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_nacimiento',
            field=models.CharField(max_length=60, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(max_length=20, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=60, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numero_cedula',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfil_activo',
            field=models.BooleanField(default=True, verbose_name='Perfil activo/inactivo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=60, verbose_name='URL personal'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono_celular',
            field=models.CharField(max_length=15, verbose_name='Número de teléfono celular'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número de teléfono convencional'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='activar_en_front',
            field=models.BooleanField(default=True, verbose_name='Visible/no visible'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargo_desempenado',
            field=models.CharField(max_length=100, verbose_name='Cargo/puesto'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcion_funciones',
            field=models.TextField(max_length=500, verbose_name='Descripción de responsabilidades'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Correo electrónico empresarial'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de incorporación'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugar_empresa',
            field=models.CharField(max_length=50, verbose_name='Dirección de la empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombre_contacto',
            field=models.CharField(max_length=100, verbose_name='Responsable de contacto'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombre_empresa',
            field=models.CharField(max_length=50, verbose_name='Empresa empleadora'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales', verbose_name='Perfil registrado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='ruta_certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_laborales/', verbose_name='Constancia laboral'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitio_web_empresa',
            field=models.URLField(blank=True, max_length=100, verbose_name='URL de la empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefono_contacto',
            field=models.CharField(max_length=60, verbose_name='Número de contacto de empresa'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='activar_en_front',
            field=models.BooleanField(default=True, verbose_name='Visible/no visible'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='clasificador',
            field=models.CharField(max_length=100, verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='nombre_recurso',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales', verbose_name='Perfil registrado'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='activar_en_front',
            field=models.BooleanField(default=True, verbose_name='Visible/no visible'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fecha_producto',
            field=models.DateField(verbose_name='Fecha de realización'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='nombre_producto',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales', verbose_name='Perfil registrado'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='activar_en_front',
            field=models.BooleanField(default=True, verbose_name='Visible/no visible'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción de la acreditación'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='entidad_patrocinadora',
            field=models.CharField(max_length=100, verbose_name='Institución patrocinadora'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fecha_reconocimiento',
            field=models.DateField(verbose_name='Fecha de acreditación'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable de contacto'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales', verbose_name='Perfil registrado'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='ruta_certificado',
            field=models.FileField(blank=True, null=True, upload_to='reconocimientos/', verbose_name='Acreditación'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número de contacto institucional'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='tipo_reconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=50, verbose_name='Naturaleza de acreditación'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='activar_en_front',
            field=models.BooleanField(default=True, verbose_name='Visible/no visible'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado_producto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, verbose_name='Condición del producto'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombre_producto',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_de_vida.datospersonales', verbose_name='Perfil registrado'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valor_bien',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de venta'),
        ),
    ]
