# Generated by Django 6.0 on 2026-01-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_de_vida', '0002_alter_cursorealizado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursorealizado',
            options={'verbose_name': 'Formación realizada', 'verbose_name_plural': 'Formación realizada'},
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='descripcion_funciones',
            new_name='descripcion_functions',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='tipo_reconocimiento',
            field=models.CharField(choices=[('Académica', 'Académica'), ('Pública', 'Pública'), ('Privada', 'Privada')], max_length=50, verbose_name='Naturaleza de acreditación'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado_producto',
            field=models.CharField(choices=[('En buen estado', 'En buen estado'), ('Estado aceptable', 'Estado aceptable')], max_length=40, verbose_name='Condición del producto'),
        ),
    ]
