# Generated by Django 6.0 on 2026-01-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_de_vida', '0003_alter_cursorealizado_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='descripcion_functions',
            new_name='descripcion_funciones',
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='venta_garage/', verbose_name='Fotografía'),
        ),
    ]
